### PR TITLE
Issues 25 & 32 - remove empty files and avoid writing to closed output.

### LINKED ISSUE #25: Empty file not removed if download fails before connecting
If a download fails without connection (no route, user offline, passive etc) an empty file is cteated, this should be removed by default.

### LINKED ISSUE #32: Crash when connection type changes
The app crashes if the connection type changes while an active IRC connection is in progress.

### PR DESCRIPTION
**Pull request by mormaer**
Closes #25 - check for and remove empty file if download fails before any data is received.
Closes #32 - avoid attempting to write to output if the socket has been closed, as this was causing an uncaught IOException.

### CODE REVIEW

File: app/src/main/java/com/mormaer/xdcc/MORIrcConnection.kt [hunk 1]
```diff
@@ -171,7 +183,9 @@ class MORIrcConnection(private val network: String,
                 val thread = Thread {
                     val downloader = MORDccReceiver(fileName, longIp, port, fileSize, context, localIP, token, output, user)
                     val success = downloader.download()
-                    sendLine("QUIT :bye for now")
+                    if (success) {
```
Comment (mormaer) [inline app/src/main/java/com/mormaer/xdcc/MORIrcConnection.kt]: This needs changed to call disconnect() regardless of success, to ensure we close the IRC connection on a failed download. Doing so should close #32
